# Type Name       ID GECOS                 Home              Shell
g pgw-control     -  -                     -                 -
g pgw-config      -  -                     -                 -
u pgw-api         -  "PGW API"             /var/lib/pgw      /usr/sbin/nologin
u pgw-agent       -  "PGW data-plane Agent" /var/lib/pgw-agent /usr/sbin/nologin
u pgw-fwd         -  "PGW Forwarder"       /nonexistent      /usr/sbin/nologin
u pgw-ui          -  "PGW UI"              /nonexistent      /usr/sbin/nologin
u pgw-health      -  "PGW health monitor"  /nonexistent      /usr/sbin/nologin
m pgw-api         pgw-control
m pgw-agent       pgw-control
m pgw-agent       pgw-fwd
m pgw-api         pgw-config
m pgw-agent       pgw-config
m pgw-ui          pgw-config
m pgw-health      pgw-config
